apiVersion: v1
kind: Service
metadata:
  name: churn-api-service
spec:
  type: LoadBalancer
  selector:
    app: churn-api
  ports:
    - protocol: TCP
      port: 8000   # <-- port exposed inside cluster
      targetPort: 8000 # <-- forwarded to container